# Generated by Django 5.1.15 on 2026-06-15 13:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "project_type",
                    models.CharField(
                        choices=[
                            ("commercial", "Commercial"),
                            ("residential", "Residential"),
                            ("infrastructure", "Infrastructure"),
                            ("industrial", "Industrial"),
                        ],
                        max_length=40,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=220)),
                ("description", models.TextField(blank=True)),
                ("client_name", models.CharField(blank=True, max_length=180)),
                ("consultant_name", models.CharField(blank=True, max_length=180)),
                ("consultant_phone", models.CharField(blank=True, max_length=40)),
                ("consultant_email", models.EmailField(blank=True, max_length=254)),
                ("contractor_name", models.CharField(blank=True, max_length=180)),
                ("contractor_phone", models.CharField(blank=True, max_length=40)),
                ("contractor_email", models.EmailField(blank=True, max_length=254)),
                ("planned_start", models.DateField(blank=True, null=True)),
                ("planned_finish", models.DateField(blank=True, null=True)),
                ("revised_finish", models.DateField(blank=True, null=True)),
                (
                    "size_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("is_archived", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["company", "is_archived"],
                        name="projects_pr_company_7b1edd_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"), name="uniq_project_name_per_company"
                    )
                ],
            },
        ),
    ]
