# Generated by Django 5.1.15 on 2026-06-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="code",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="project",
            name="currency",
            field=models.CharField(default="AED", max_length=8),
        ),
        migrations.AddField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
    ]
