# Generated by Django 5.1.15 on 2026-06-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
        ("projects", "0003_projectscope_activity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="phase_name",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="activity",
            name="row_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["scope", "row_index"], name="projects_ac_scope_i_10cd29_idx"
            ),
        ),
    ]
