# Generated by Django 5.1.15 on 2026-06-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
        ("projects", "0005_projectmember"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="activity",
            name="projects_ac_scope_i_10cd29_idx",
        ),
        migrations.AddField(
            model_name="activity",
            name="subzone_code",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="activity",
            name="subzone_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="projectscope",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("phase", "Phase"),
                    ("zone", "Zone"),
                    ("building", "Building"),
                    ("area", "Area"),
                    ("task", "Task"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["scope", "subzone_index"], name="projects_ac_scope_i_fab217_idx"
            ),
        ),
    ]
