# Generated by Django 5.1.15 on 2026-06-16 05:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
        ("projects", "0007_milestone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgressSnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                (
                    "overall_progress",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("breakdown", models.JSONField(blank=True, default=dict)),
                ("zones", models.JSONField(blank=True, default=list)),
                ("source", models.CharField(blank=True, max_length=200)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_snapshots",
                        to="accounts.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "indexes": [
                    models.Index(
                        fields=["project", "date"],
                        name="projects_pr_project_9b5b2c_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "date"), name="uniq_snapshot_per_date"
                    )
                ],
            },
        ),
    ]
