# Generated by Django 5.1.15 on 2026-06-16 12:40

import apps.projects.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
        ("projects", "0010_projectscopeaccess"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.projects.models.project_image_key),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("site_photo", "Site Photo"),
                            ("cover", "Cover Image"),
                            ("logo_left", "Left Logo"),
                            ("logo_right", "Right Logo"),
                        ],
                        default="site_photo",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=180)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_images",
                        to="accounts.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="projects.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_project_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["image_type", "sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "image_type", "sort_order"],
                        name="projects_pr_project_0f69c8_idx",
                    ),
                    models.Index(
                        fields=["company", "created_at"],
                        name="projects_pr_company_362315_idx",
                    ),
                ],
            },
        ),
    ]
