# Generated by Django 5.1.15 on 2026-06-17 02:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
        ("projects", "0011_projectimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDelay",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("impact_days", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("resolved", "Resolved")],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_delays",
                        to="accounts.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delays",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-date"],
                "indexes": [
                    models.Index(
                        fields=["project", "sort_order"],
                        name="projects_pr_project_d2e01c_idx",
                    )
                ],
            },
        ),
    ]
