# Generated by Django 5.1.15 on 2026-06-23 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_progressentry_progressimage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectscope",
            name="discipline",
            field=models.CharField(
                blank=True,
                choices=[
                    ("concrete", "Concrete"),
                    ("architecture", "Architecture"),
                    ("electrical", "Electrical"),
                    ("mechanical", "Mechanical"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="projectscope",
            name="planned_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectscope",
            name="planned_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectscope",
            name="revised_finish",
            field=models.DateField(blank=True, null=True),
        ),
    ]
