# Generated by Django 5.1.15 on 2026-06-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0014_projectscope_discipline_projectscope_planned_finish_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="progresssnapshot",
            name="scopes",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
