# Generated by Django 5.1.15 on 2026-06-23 12:48

import apps.projects.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
        ("projects", "0015_progresssnapshot_scopes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashFlowEntry",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("month", models.DateField()),
                (
                    "planned",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflow_entries",
                        to="accounts.company",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cashflow_entries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["month"],
                "indexes": [
                    models.Index(
                        fields=["project", "month"],
                        name="projects_ca_project_8956b8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "month"), name="uniq_cashflow_month"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=16),
                ),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.projects.models.invoice_image_key,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "sort_order"],
                        name="projects_in_project_56f465_idx",
                    ),
                    models.Index(
                        fields=["project", "-date"],
                        name="projects_in_project_481d73_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Submittal",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "submittal_type",
                    models.CharField(
                        choices=[
                            ("shop_drawing", "Shop Drawing"),
                            ("material", "Material"),
                        ],
                        default="shop_drawing",
                        max_length=20,
                    ),
                ),
                (
                    "discipline",
                    models.CharField(
                        choices=[
                            ("concrete", "Concrete"),
                            ("architecture", "Architecture"),
                            ("electrical", "Electrical"),
                            ("mechanical", "Mechanical"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("under_review", "Under Review"),
                            ("approved", "Approved"),
                            ("approved_with_comments", "Approved with comments"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=30,
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=80)),
                ("date", models.DateField(blank=True, null=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.projects.models.submittal_attachment_key,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submittals",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_submittals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submittals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-date", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "sort_order"],
                        name="projects_su_project_d9d883_idx",
                    ),
                    models.Index(
                        fields=["project", "status"],
                        name="projects_su_project_5a9872_idx",
                    ),
                ],
            },
        ),
    ]
