# Generated by Django 5.1.15 on 2026-06-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="progresssubmission",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="progresssubmission",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
