# Generated by Django 5.1.15 on 2026-06-30 11:23

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_progresssubmission_decided_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="source_workbook",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.projects.models.source_workbook_key,
            ),
        ),
    ]
