# Generated by Django 5.1.15 on 2026-06-30 11:36

import apps.projects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_project_source_workbook"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="p6_export",
            field=models.FileField(
                blank=True, null=True, upload_to=apps.projects.models.p6_export_key
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="p6_export_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="p6_export_status",
            field=models.CharField(
                choices=[
                    ("idle", "Idle"),
                    ("generating", "Generating"),
                    ("ready", "Ready"),
                    ("error", "Error"),
                ],
                default="idle",
                max_length=12,
            ),
        ),
    ]
