# Generated by Django 5.1.15 on 2026-07-05 11:43
#
# NOTE: this per-project permissions field was superseded by migration 0022,
# which drops it again — module access moved to company role permissions
# instead (see apps.accounts.constants). Kept as a no-op schema step so the
# migration history stays linear for anyone who already applied it.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_p6_export_project_p6_export_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
