# Generated by Django 5.1.15 on 2026-07-05 11:43

from django.db import migrations, models

from apps.projects.permissions_catalog import ALL_PROJECT_PERMISSIONS


def grant_existing_members_full_access(apps, schema_editor):
    """Existing members had implicit full access under the old company-permission
    gating — preserve that so enforcement doesn't suddenly lock anyone out."""
    ProjectMember = apps.get_model("projects", "ProjectMember")
    ProjectMember.objects.update(permissions=list(ALL_PROJECT_PERMISSIONS))


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_project_p6_export_project_p6_export_started_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="permissions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.RunPython(grant_existing_members_full_access, migrations.RunPython.noop),
    ]
