# Generated by Django 5.1.15 on 2026-07-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_projectmember_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectmember",
            name="permissions",
        ),
    ]
