# Generated by Django 5.1.15 on 2026-07-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_remove_projectmember_permissions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectmember",
            options={"ordering": ["created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="projectmember",
            name="projects_pr_project_5b8833_idx",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="role",
        ),
    ]
