# Generated by Django 5.1.15 on 2026-07-06 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_company_admin_variations_perms"),
        ("projects", "0026_variation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="variation",
            name="reference",
        ),
        migrations.AddField(
            model_name="variation",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="variation",
            name="decided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decided_variations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="variation",
            name="number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="variation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="variation",
            index=models.Index(
                fields=["project", "kind", "status"],
                name="projects_va_project_09df9e_idx",
            ),
        ),
    ]
