# Generated by Django 5.1.15 on 2026-07-06 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_variation_workflow"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="variation",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="variation",
            name="projects_va_project_04cdd4_idx",
        ),
        migrations.RemoveField(
            model_name="variation",
            name="date",
        ),
    ]
