# Generated by Django 5.1.15 on 2026-07-08 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_variation_drop_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectscope",
            name="scope_type",
            field=models.CharField(
                choices=[
                    ("stage", "Stage"),
                    ("phase", "Phase"),
                    ("zone", "Zone"),
                    ("building", "Building"),
                    ("area", "Area"),
                    ("task", "Task"),
                ],
                max_length=20,
            ),
        ),
    ]
