# Generated by Django 5.1.15 on 2026-07-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_scope_stage_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="planned_finish",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="planned_start",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="advance_payment",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="eot_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="forecast_finish",
            field=models.DateField(blank=True, null=True),
        ),
    ]
