# Generated by Django 5.1.15 on 2026-07-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_activity_planned_finish_activity_planned_start_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="budgeted_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="earned_value_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="original_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="remaining_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="total_float",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="activity",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=18),
        ),
    ]
