# Generated by Django 5.1.15 on 2026-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0031_activity_budgeted_cost_activity_earned_value_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="imported_progress_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
