# Generated by Django 5.1.15 on 2026-07-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0032_project_imported_progress_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="imported_planned_progress_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
