# Generated by Django 5.1.15 on 2026-08-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_project_imported_planned_progress_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("site_photo", "Site Photo"),
                    ("cover", "Cover Image"),
                    ("logo_left", "Left Logo"),
                    ("logo_right", "Right Logo"),
                    ("logo", "Additional Logo"),
                ],
                default="site_photo",
                max_length=20,
            ),
        ),
    ]
