# Generated by Django 5.1.15 on 2026-08-05 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_alter_projectimage_image_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="approved_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="contract_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="forecast_cost",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
