# Generated by Django 5.1.15 on 2026-08-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0035_project_approved_value_project_contract_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contractor_consultant",
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name="project",
            name="part_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="part_completion_revised",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="part_delay_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="part_forecast_completion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="project_delay_days",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="revised_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
    ]
