# Generated by Django 5.1.15 on 2026-08-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0036_project_contractor_consultant_project_part_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="project_delay_days",
        ),
        migrations.RemoveField(
            model_name="project",
            name="revised_amount",
        ),
    ]
