# Generated by Django 5.1.15 on 2026-08-10 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_company_admin_master_data_perm"),
        ("projects", "0037_remove_project_project_delay_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="scope",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="milestones",
                to="projects.projectscope",
            ),
        ),
        migrations.AddIndex(
            model_name="milestone",
            index=models.Index(
                fields=["project", "scope"], name="projects_mi_project_469569_idx"
            ),
        ),
    ]
