# Generated by Django 5.1.15 on 2026-08-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0038_milestone_scope_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectscope",
            name="label",
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
