# Generated by Django 5.1.15 on 2026-08-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0039_projectscope_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="milestone",
            name="progress_percent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
