# Generated by Django 5.1.15 on 2026-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0040_milestone_progress_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="actual_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="baseline_duration",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="activity",
            name="schedule_performance_index",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="schedule_variance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=18, null=True
            ),
        ),
    ]
