# Generated by Django 5.1.15 on 2026-08-10 13:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_company_admin_master_data_perm"),
        (
            "projects",
            "0041_activity_actual_duration_activity_baseline_duration_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="part_amount",
        ),
        migrations.RemoveField(
            model_name="project",
            name="part_completion_revised",
        ),
        migrations.RemoveField(
            model_name="project",
            name="part_delay_days",
        ),
        migrations.RemoveField(
            model_name="project",
            name="part_forecast_completion",
        ),
        migrations.CreateModel(
            name="PartScope",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=16, null=True
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_revised", models.DateField(blank=True, null=True)),
                ("forecast_completion", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_scopes",
                        to="accounts.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_part_scopes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="part_scopes",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "-created_at"],
                        name="projects_pa_project_57c1ea_idx",
                    )
                ],
            },
        ),
    ]
