# Generated by Django 5.1.15 on 2026-08-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_remove_project_part_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_payment_currency',
            field=models.CharField(default='AED', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_value_currency',
            field=models.CharField(default='AED', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_currency',
            field=models.CharField(default='AED', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='contract_value_currency',
            field=models.CharField(default='AED', max_length=8),
        ),
        migrations.AddField(
            model_name='project',
            name='forecast_cost_currency',
            field=models.CharField(default='AED', max_length=8),
        ),
    ]
