# Generated by Django 5.1.15 on 2026-08-30 08:48

import apps.projects.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_admin_master_data_perm'),
        ('projects', '0043_project_advance_payment_currency_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleImport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.projects.models.schedule_import_file_key)),
                ('activity_count', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_imports', to='accounts.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_imports', to='projects.project')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_imports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='schedule_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='projects.scheduleimport'),
        ),
        migrations.AddField(
            model_name='projectscope',
            name='schedule_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scopes', to='projects.scheduleimport'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['project', 'schedule_import'], name='projects_ac_project_dc6924_idx'),
        ),
        migrations.AddIndex(
            model_name='projectscope',
            index=models.Index(fields=['project', 'schedule_import'], name='projects_pr_project_723e87_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleimport',
            index=models.Index(fields=['project', '-date'], name='projects_sc_project_ba1c30_idx'),
        ),
    ]
