# Generated by Django 5.1.15 on 2026-09-02 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_backfill_schedule_import'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='schedule_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
