# Generated by Django 5.1.15 on 2026-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_activity_schedule_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresssnapshot',
            name='forecast_progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='progresssnapshot',
            name='planned_progress',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
