# Generated by Django 5.1.15 on 2026-09-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_progresssnapshot_forecast_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='subcontractor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='project',
            name='subcontractor_name',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='project',
            name='subcontractor_phone',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
