# Generated by Django 5.1.15 on 2026-09-07 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_admin_master_data_perm'),
        ('projects', '0048_project_subcontractor_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progresssnapshot',
            options={},
        ),
        migrations.CreateModel(
            name='ProgressCurvePoint',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('early_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('late_planned', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('actual', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_curve_points', to='accounts.company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curve_points', to='projects.project')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['project', 'date'], name='projects_pr_project_af4572_idx')],
                'constraints': [models.UniqueConstraint(fields=('project', 'date'), name='uniq_curve_point_per_date')],
            },
        ),
    ]
