# Generated by Django 5.1.15 on 2026-09-07 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_alter_progresssnapshot_options_progresscurvepoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='schedule_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.scheduleimport'),
        ),
    ]
