# Generated by Django 5.1.15 on 2026-09-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0051_backfill_milestone_schedule_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectscope',
            name='scope_type',
            field=models.CharField(choices=[('stage', 'Stage'), ('phase', 'Phase'), ('zone', 'Zone'), ('building', 'Building'), ('area', 'Area'), ('task', 'Task'), ('sub_area', 'Sub-area'), ('part', 'Part'), ('unit', 'Unit'), ('level', 'Level'), ('discipline', 'Discipline'), ('sub_discipline', 'Sub-discipline')], max_length=20),
        ),
    ]
