# Generated by Django 5.1.15 on 2026-09-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_project_currency_follows_its_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectscope',
            name='is_placeholder',
            field=models.BooleanField(default=False),
        ),
    ]
