# Generated by Django 5.1.15 on 2026-09-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0054_scope_placeholder_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='approved_finish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
