# Generated by Django 5.1.15 on 2026-09-13 13:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_admin_master_data_perm'),
        ('projects', '0056_dashboard_import_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPanels',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_panels', to='accounts.company')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_panels', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'dashboard panels',
            },
        ),
    ]
