# Generated by Django 5.1.15 on 2026-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="model",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
