# Generated by Django 5.1.15 on 2026-07-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_chatsession_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="proposal_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("cancelled", "Cancelled"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "proposal_status"],
                name="ai_assistan_session_67a214_idx",
            ),
        ),
    ]
