# Generated by Django 5.1.15 on 2026-08-02 13:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0007_company_ai_enabled"),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=80)),
                ("symbol", models.CharField(blank=True, max_length=8)),
                ("is_default", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["sort_order", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "code"),
                        name="uniq_currency_code_per_company",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectPriority",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_priorities",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "project priorities",
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"),
                        name="uniq_project_priority_per_company",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProjectType",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_types",
                        to="accounts.company",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("company", "name"), name="uniq_project_type_per_company"
                    )
                ],
            },
        ),
    ]
