# Generated by Django 5.1.15 on 2026-09-06 09:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_company_admin_master_data_perm'),
        ('master_data', '0004_backfill_parties_from_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubContractor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcontractors', to='accounts.company')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='uniq_subcontractor_per_company')],
            },
        ),
    ]
