# Generated by Django 5.1.15 on 2026-06-15 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="company",
            name="phone_number",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="company",
            name="website",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
