# Generated by Django 5.1.15 on 2026-06-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounts",
            "0002_company_address_company_email_company_phone_number_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="is_system",
            field=models.BooleanField(default=False),
        ),
    ]
