# Generated by Django 5.1.15 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_company_admin_variations_perms"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="ai_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
