# Generated by Django 5.1.15 on 2026-06-16 13:46

import apps.reports.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_backfill_default_roles"),
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="report",
            name="report_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ReportImage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.reports.models.report_image_key),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("cover", "Cover Image"),
                            ("progress", "Progress Photo"),
                            ("attachment", "Attachment"),
                        ],
                        default="progress",
                        max_length=20,
                    ),
                ),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_images",
                        to="accounts.company",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reports.report",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_report_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "sort_order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["report", "kind", "sort_order"],
                        name="reports_rep_report__344a42_idx",
                    )
                ],
            },
        ),
    ]
