# Generated by Django 5.1.15 on 2026-06-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_report_description_report_report_date_reportimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="scope_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
