# Generated by Django 5.1.15 on 2026-06-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0003_report_scope_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="description_html",
            field=models.TextField(blank=True),
        ),
    ]
