# Generated by Django 5.1.15 on 2026-07-06 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_report_description_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="progress_image_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
