# Generated by Django 5.1.15 on 2026-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0005_report_progress_image_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="layout_override",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
