# Generated by Django 5.1.15 on 2026-08-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0006_report_layout_override"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportimage",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cover", "Cover Image"),
                    ("progress", "Progress Photo"),
                    ("attachment", "Attachment"),
                    ("canvas", "Canvas Image"),
                ],
                default="progress",
                max_length=20,
            ),
        ),
    ]
