# Generated by Django 5.1.15 on 2026-09-13 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0055_project_approved_finish'),
        ('reports', '0009_owner_wording_and_summary_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='schedule_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='projects.scheduleimport'),
        ),
    ]
